import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
            trim:true,
        },
        email:{
            type:String,
            required:true,
            unique:true,
            trim:true,
            lowercase:true,
        },
        password:{
            type:String,
            required:true,
            minlength:8
        },
        slug:{
            type:String,
            required:true,
            trim:true,
            unique:true,
            lowercase:true
        },
        businessName:{
            type:String,
            default:"",
            trim:true,
        },
        businessDiscription:{
            type:String,
            default:"",
            trim:true,
        },
        brandName:{
            type:String,
            default:"",
            trim:true,
        },
        brandTheme:{
            type:String,
            enum:["emerald","indigo","rose","amber","slate"],
            default:"emerald",
        },
        brandAccent:{
            type:String,
            default:"#047857"
        },
        timeZone:{
            type:String,
            default:"",
        },
        googleRefereshToken:{
            type:String,
            default:"",
        },
        googleCalenderConnected:{
            type:Boolean,
            default:false,
        },
        googleCalenderId:{
            type:String,
            default:"primary"
        },
        payoutDetails:{
            accountHolder:{
                type:String,
                default:"",
                trim:true,
            },
            bankName:{
                type:String,
                default:"",
                trim:true,
            },
            accountLast4:{
                 type:String,
                default:"",
                trim:true,
            },
            IFSC:{
                 type:String,
                default:"",
                trim:true,
                uppercase:true,
            },
            upiId:{
                 type:String,
                default:"",
                trim:true,
            },
            isComplete:{
                type:Boolean,
                default:false,
            },
            updatedAt:{
                type:Date,
            }
        }
    },{timeseries:true}

);

const User = mongoose.model("User",userSchema);
export default User;